config/routes.rb
Rails.application.routes.draw do
  resources :orders
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
  has_one :delivery, dependent: :destroy
  accepts_nested_attributes_for :delivery
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
    @order.build_delivery
  end

  def create
    @order = Order.new(order_params)
    binding.pry
    delivery_time = GoogleMatrixApi::ByAddress.call(order_params[:delivery_attributes])
    @order[:journey_time] = delivery_time
    if @order.save
      redirect_to order_path, notice: 'Order has been created successfully'
    else
      render 'new'
    end
  end

  def update
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit(:customer_name, :delivery_due, delivery_attributes: [ :start_address, :end_address ])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToshiApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% render 'shared/flash' %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<h1>Orders Page</h1>
<p>Here you can view all your orders</p>

<h4>Create new order: <%= link_to "New Order", new_order_path  %></h4>

<% @orders.each do |order| %>
  <div class="container card text-center shadow rounded mb-3 mt-3">
    <div class="card-header">
     <strong> <%= order.customer_name %> </strong>
    </div>
    <div class="card-body">
       <p class="card-text">Journey Time: <%= order.journey_time %> mins </p>
       <p class="card-text">Delivery Due: <%= order.delivery_due %></p>
       <p class="card-text">Starting location: <%= order.delivery.start_address %></p>
       <p class="card-text">End location: <%= order.delivery.end_address %></p>
    </div>
    <div class="mb-3">
      <%= link_to "Show", order_path(order), class: "btn btn-primary" %>
      <%= link_to "Edit", edit_order_path(order), class: "btn btn-outline-success " %></>
      <%= link_to "Delete", order_path(order), class: "btn btn-danger", method: :delete %>
  </div>
  </div>
<% end %>

app/views/orders/new.html.erb
<% if @order.errors.any? %>
  <h2>The following errors prevented the order from being saved</h2>
  <ul>
    <% @order.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= simple_form_for(@order) do |f| %>
  <div class="form-inputs mt-5">
    <%= f.input :customer_name %>
    <%= f.input :delivery_due, as: :datetime %>

    <%= f.simple_fields_for :delivery do |form| %>
      <%= form.input :start_address %>
      <%= form.input :end_address %>
    <% end %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orders/show.html.erb
<h1>Customer Name: <%= @order.customer_name %></h1>

<ul>
  <li>Date Due: <%=@order.delivery_due %></li>
  <li>Journey (minutes): <%=@order.journey_time %></li>
  <li>Starting Location: <%=@order.delivery.start_address %></li>
  <li>End Location: <%=@order.delivery.end_address %></li>

</ul>
<%= link_to 'Home', orders_path %>

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>